#!/usr/bin/env zsh
# ZSH 4+ script to retrieve archives in a variety of mechanisms
# This should only be used to fetch brand new archives into an empty
# directory!  You have been warned!
ARCHIVES_PATH=$HOME/archives/mbox-archives.conf

if [ $# -ge 1 ]; then
  ARCHIVES_PATH="$1"
fi

if [ ! -f $ARCHIVES_PATH ] ; then
  echo $ARCHIVES_PATH not found.  Exiting.
  exit 1
fi

source $ARCHIVES_PATH

for i in ${ARCHIVES} ; do
    $SCRIPT_DIR/catchup-archive ${${(P)i}[1]} $ARCHIVES_PATH
done
