#!/bin/sh
#
# rundig
#
# $Id: rundig 124332 2005-01-06 01:03:34Z jerenkrantz $
#
# This is Justin's modified script to create a search database for ht://Dig
# with mod_mbox.
DBDIR=/x1/mail-archives/htdig-db
COMMONDIR=/usr/share/htdig
BINDIR=/usr/bin

# To help debug problems, try running rundig -vvv
# This will add lots of debugging output to all of the programs
stats="-s" opts= alt=
for arg
do
    case "$arg" in
    -a)  alt="$arg" ;;
    -s)  stats="$arg" ;;
    *)   opts="$opts $arg" ;;	# e.g. -v or -c config
    esac
done

#
# Set the TMPDIR variable if you want htmerge to put files in a location
# other than the default.  This is important if you do not have enough
# disk space for the big sort that htmerge runs.  Also, be aware that
# on some systems, /tmp is a memory mapped filesystem that takes away
# from virtual memory.
#
#TMPDIR=$DBDIR
TMPDIR=/tmp
export TMPDIR

# Remove -i - do not want initial database each time.
$BINDIR/htdig $opts $stats $alt
$BINDIR/htmerge $opts $stats $alt
case "$alt" in
-a)
  ( cd $DBDIR && test -f db.docdb.work &&
    for f in *.work
    do
        mv -f $f `basename $f .work`
    done ) ;;
esac
# If you're low on disk space and you don't mind completely reindexing
# every time you run this script, you can always
# rm $DBDIR/db.wordlist
# OR
# If you'd rather run update digs all the time with the minimal databases
# Keep only the following files (and don't call htdig with -i):
# db.docdb, db.docdb.work, db.docs.index, db.wordlist.work, db.words.db
$BINDIR/htnotify $opts
# If you want to use the soundex and (or) metaphone fuzzy matchings,
# Uncomment the following line
$BINDIR/htfuzzy $opts soundex metaphone

#
# Create the endings and synonym databases if they don't exist
# or if they're older than the files they're generated from.
# These databases are semi-static, so even if pages change,
# these databases will not need to be rebuilt.
#
if [ "`ls -t $COMMONDIR/english.0 $COMMONDIR/word2root.db 2>/dev/null | sed 1q`" = \
	"$COMMONDIR/english.0" ]
then
    $BINDIR/htfuzzy $opts endings
fi

if [ "`ls -t $COMMONDIR/synonyms $COMMONDIR/synonyms.db 2>/dev/null | sed 1q`" = \
	"$COMMONDIR/synonyms" ]
then
    $BINDIR/htfuzzy $opts synonyms
fi
